# Generated by Django 5.0.4 on 2024-05-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('lobbyID', models.IntegerField(primary_key=True, serialize=False)),
                ('lobbyCount', models.IntegerField()),
                ('lobbyList', models.TextField()),
                ('accessBlocked', models.IntegerField()),
            ],
        ),
    ]
