# Generated by Django 5.0.4 on 2024-05-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='roleMatching',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
    ]
