# Generated by Django 5.0.4 on 2024-05-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='lobbyID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
