# Generated by Django 5.0.4 on 2024-05-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_lobby_rolematching'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='status',
            field=models.TextField(default='lobby'),
            preserve_default=False,
        ),
    ]
