# Generated by Django 5.0.6 on 2024-05-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_lobby_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='roleMatching',
            new_name='roleDistribution',
        ),
        migrations.RemoveField(
            model_name='lobby',
            name='lobbyCount',
        ),
        migrations.AddField(
            model_name='lobby',
            name='messages',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
