# Generated by Django 5.0.6 on 2024-05-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_rolematching_lobby_roledistribution_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='accessBlocked',
            new_name='dBAccessBlocked',
        ),
    ]
