# Generated by Django 5.0.6 on 2024-05-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_accessblocked_lobby_dbaccessblocked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lobby',
            old_name='messages',
            new_name='observations',
        ),
    ]
