# Generated by Django 5.0.6 on 2024-05-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_messages_lobby_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='dBAccessBlocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='lobbyList',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='observations',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='roleDistribution',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='status',
            field=models.TextField(default='lobby'),
        ),
    ]
