# Generated by Django 5.0.6 on 2024-05-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_lobby_dbaccessblocked_alter_lobby_lobbylist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='wwRoles',
            field=models.TextField(default='{}'),
        ),
    ]
